/**
 * Image carousel enhancement for [grid mode=carousel] blocks
 * (markup generated by src/lib/markdown/remark-image-grid.ts).
 *
 * Handles slide navigation: prev/next buttons, dots, keyboard and
 * scroll-snap position syncing. The lightbox is handled separately by
 * image-enhancer (PhotoSwipe) through the standard .markdown-image flow.
 */

const CAROUSEL_SELECTOR = '.image-carousel[data-mode="carousel"]';

// AbortController per carousel — abort removes every listener bound with its signal
const controllers = new WeakMap<HTMLElement, AbortController>();

function initCarousel(carousel: HTMLElement): void {
  const track = carousel.querySelector<HTMLElement>('.image-carousel__track');
  const slides = Array.from(carousel.querySelectorAll<HTMLElement>('.image-carousel__slide'));
  if (!track || slides.length < 2) return;

  carousel.dataset.carouselInitialized = 'true';

  const dots = Array.from(carousel.querySelectorAll<HTMLButtonElement>('.image-carousel__dot'));
  const prevButton = carousel.querySelector<HTMLButtonElement>('.image-carousel__nav--prev');
  const nextButton = carousel.querySelector<HTMLButtonElement>('.image-carousel__nav--next');

  const controller = new AbortController();
  controllers.set(carousel, controller);
  const { signal } = controller;

  let activeIndex = 0;
  let rafId = 0;
  // While a programmatic smooth scroll is in flight, skip scroll-position
  // syncing so the dots don't flicker through intermediate slides.
  let programmaticScroll = false;
  let scrollSettleTimer: ReturnType<typeof setTimeout> | undefined;

  const setActive = (index: number) => {
    if (index === activeIndex) return;
    activeIndex = index;
    slides.forEach((slide, i) => {
      slide.classList.toggle('is-active', i === index);
    });
    dots.forEach((dot, i) => {
      dot.classList.toggle('active', i === index);
      if (i === index) dot.setAttribute('aria-current', 'true');
      else dot.removeAttribute('aria-current');
    });
  };

  const scrollToSlide = (index: number) => {
    // Wrap around at both ends
    const target = ((index % slides.length) + slides.length) % slides.length;
    const slide = slides[target];
    const left = slide.offsetLeft - (track.clientWidth - slide.clientWidth) / 2;
    programmaticScroll = true;
    setActive(target);
    const reduceMotion = window.matchMedia('(prefers-reduced-motion: reduce)').matches;
    track.scrollTo({ left, behavior: reduceMotion ? 'auto' : 'smooth' });
  };

  const syncFromScroll = () => {
    rafId = 0;
    const center = track.scrollLeft + track.clientWidth / 2;
    let closest = activeIndex;
    let minDistance = Number.POSITIVE_INFINITY;
    slides.forEach((slide, i) => {
      const distance = Math.abs(slide.offsetLeft + slide.clientWidth / 2 - center);
      if (distance < minDistance) {
        minDistance = distance;
        closest = i;
      }
    });
    setActive(closest);
  };

  track.addEventListener(
    'scroll',
    () => {
      clearTimeout(scrollSettleTimer);
      scrollSettleTimer = setTimeout(() => {
        programmaticScroll = false;
      }, 150);
      if (programmaticScroll) return;
      if (!rafId) rafId = requestAnimationFrame(syncFromScroll);
    },
    { passive: true, signal },
  );

  prevButton?.addEventListener('click', () => scrollToSlide(activeIndex - 1), { signal });
  nextButton?.addEventListener('click', () => scrollToSlide(activeIndex + 1), { signal });
  dots.forEach((dot, i) => {
    dot.addEventListener('click', () => scrollToSlide(i), { signal });
  });

  track.addEventListener(
    'keydown',
    (event) => {
      if (event.key === 'ArrowLeft') {
        event.preventDefault();
        scrollToSlide(activeIndex - 1);
      } else if (event.key === 'ArrowRight') {
        event.preventDefault();
        scrollToSlide(activeIndex + 1);
      } else if (event.key === 'Home') {
        event.preventDefault();
        scrollToSlide(0);
      } else if (event.key === 'End') {
        event.preventDefault();
        scrollToSlide(slides.length - 1);
      }
    },
    { signal },
  );

  // Slides without a build-time |WxH size hint: derive the aspect ratio
  // from the image's natural dimensions once it loads.
  slides.forEach((slide) => {
    if (slide.style.aspectRatio) return;
    const image = slide.querySelector<HTMLImageElement>('img');
    if (!image) return;
    const applyRatio = () => {
      if (image.naturalWidth > 0 && image.naturalHeight > 0) {
        slide.style.aspectRatio = `${image.naturalWidth} / ${image.naturalHeight}`;
      }
    };
    if (image.complete) applyRatio();
    else image.addEventListener('load', applyRatio, { once: true, signal });
  });

  signal.addEventListener('abort', () => {
    clearTimeout(scrollSettleTimer);
    if (rafId) cancelAnimationFrame(rafId);
  });
}

export function enhanceCarousels(container: Element): void {
  container.querySelectorAll<HTMLElement>(CAROUSEL_SELECTOR).forEach((carousel) => {
    if (carousel.dataset.carouselInitialized === 'true') return;
    initCarousel(carousel);
  });
}

export function cleanupCarousels(container: Element): void {
  container.querySelectorAll<HTMLElement>(CAROUSEL_SELECTOR).forEach((carousel) => {
    controllers.get(carousel)?.abort();
    controllers.delete(carousel);
    delete carousel.dataset.carouselInitialized;
  });
}
