export const momentsLabels = {
  allChannels: '全部频道',
  back: '返回上一页',
  channel: '频道',
  channelNavigation: '碎碎念频道',
  cacheNotice: '内容可能有最多 5 分钟延迟',
  collapse: '收起全文',
  copied: '已复制',
  copyFailed: '复制失败，请手动复制',
  copyLink: '复制链接',
  emptyChannel: '这个频道还没有消息',
  emptyMessage: '空消息',
  expand: '展开全文',
  feedUnavailable: '动态内容服务暂时无法连接，博客文章仍可正常浏览。',
  image: '图片',
  mediaMore: '另有 {count} 个媒体',
  mediaMessage: '媒体消息',
  mediaProcessing: '媒体处理中',
  mediaUnavailable: '媒体暂不可用',
  newer: '较新一条',
  newest: '最新发布',
  noChannels: '暂无可见频道',
  noResults: '没有找到匹配的碎碎念',
  notFound: '没有找到这条碎碎念',
  notFoundDescription: '链接可能已失效，或内容不属于当前频道。',
  older: '较早一条',
  olderContent: '加载更早内容',
  loadingEarlier: '正在加载更早内容',
  loadedEarlier: '已加载更早内容',
  allLoaded: '已加载全部内容',
  loadEarlierFailed: '加载失败，请重试',
  openDocument: '打开文件',
  permalink: '永久链接',
  pagination: '碎碎念分页',
  rateLimited: '服务暂时限制了请求，请稍后重试。',
  rateLimitedTitle: '请求过于频繁',
  relevance: '相关度',
  retry: '重试',
  search: '搜索碎碎念',
  searchForm: '搜索碎碎念内容',
  searchEmpty: '输入关键词，搜索所有公开频道的消息',
  searchHint: '请输入至少 3 个 Unicode 字符',
  searchPlaceholder: '输入至少 3 个字符',
  searchQuery: '搜索关键词',
  searchResults: '搜索结果',
  searchTooLong: '搜索内容不能超过 200 个 Unicode 字符',
  sort: '排序',
  submitSearch: '搜索碎碎念',
  updated: '已更新',
  unavailableTitle: '碎碎念暂时不可用',
  contextNavigation: '相邻碎碎念',
  tags: '标签',
  video: '视频',
  audio: '音频',
  document: '文件',
  viewSource: '查看源消息',
} as const;

export const cursorPaginationLabels = {
  next: momentsLabels.olderContent,
  back: momentsLabels.back,
  navigation: momentsLabels.pagination,
  loading: momentsLabels.loadingEarlier,
  loaded: momentsLabels.loadedEarlier,
  end: momentsLabels.allLoaded,
  error: momentsLabels.loadEarlierFailed,
  retry: momentsLabels.retry,
} as const;

export const messageCardLabels = {
  updated: momentsLabels.updated,
  permalink: momentsLabels.permalink,
  copyLink: momentsLabels.copyLink,
  copied: momentsLabels.copied,
  copyFailed: momentsLabels.copyFailed,
  viewSource: momentsLabels.viewSource,
  emptyMessage: momentsLabels.emptyMessage,
  expand: momentsLabels.expand,
  collapse: momentsLabels.collapse,
  mediaProcessing: momentsLabels.mediaProcessing,
  mediaUnavailable: momentsLabels.mediaUnavailable,
  image: momentsLabels.image,
  video: momentsLabels.video,
  audio: momentsLabels.audio,
  document: momentsLabels.document,
  openDocument: momentsLabels.openDocument,
  mediaMore: momentsLabels.mediaMore,
  tags: momentsLabels.tags,
};
